#!/bin/bash
#
# config
# CREATE THE NECESARY ALIASES AT THE HOME LEVEL AND SOURCE BASH.

HD=~/.bash_config
PRE="CONFIG:"

#
# Move the existing .bash_profile and .vimrc to *.old
#
echo "$PRE Renaming old .profile and .rc files."
if [ -h ~/.bash_profile ]; then
  rm ~/.bash_profile
elif [ -f ~/.bash_profile ]; then
  mv ~/.bash_profile ~/.bash_profile.old
fi

if [ -h ~/.vimrc ]; then
  rm ~/.vimrc
elif [ -f ~/.vimrc ]; then
  mv ~/.vimrc ~/.vimrc.old
fi

# Create symlinks to the new files
echo "$PRE Linking new .profile and .rc files."
ln -s $HD/global/.bash_profile ~/.bash_profile
ln -s $HD/global/.vimrc ~/.vimrc

#
# Create and alias the colorschemes directory if necessary
#
echo "$PRE Installing VIM color schemes."

# Make sure we have a .vim directory
if [ ! -d ~/.vim ]; then
  mkdir ~/.vim
fi

# If .vim/colors is a directory or symlink, move it out of the way or delete it
if [ -d ~/.vim/colors ]; then
  mv ~/.vim/colors ~/.vim/colors.old
elif [-h ~/.vim/colors ]; then
  rm ~.vim/colors
fi

# Link the .vim/colors directory to the global color schemes directory.
ln -s $HD/global/lib/colorschemes ~/.vim/colors

#
# Create local and bin directory if necessary
#
echo "$PRE Creating necessary local directories."
if [ ! -d $HD/local ]; then
  mkdir $HD/local
  mkdir $HD/local/bin
else
  if [ ! -d $HD/local/bin ];then
    mkdir $HD/local/bin
  fi
fi

#
# Create the default vars.bash file if it is not there.
#
echo "$PRE Creating default vars.bash file."
if [ ! -f $HD/vars.bash ] && [ -f $HD/global/_vars.bash ]; then
  cp $HD/global/_vars.bash $HD/vars.bash
fi

# Open the vars file
vi ~/.bash_config/vars.bash

# Instructions for initializing
echo "$PRE Run 'source ~/.bash_profile' to initialize the configuration."
