#!/bin/bash
#
# File: svnd
# Author: Chris Albrecht
# Data: 2011/jul/27
#
# Bootstrap file to extend Subversion capabilities by hooking into Drupal
# instances.

ACTION=$1
PRE=`echo -e "${YELLOW}SVND:${RESET}"`
CROOT=~/.bash_config/global/lib/svnd

# Load the global shared toolset
source ~/.bash_config/global/lib/shared/tools.inc

# We can't proceed without an action.
if [ -z "$ACTION" ]; then
  echo "$PRE No action specified."
  exit 1
fi

# Ensure the action file exists
if [ ! -f $CROOT/$ACTION.func ]; then
  echo "$PRE Action file not found."
  exit 1
fi

# Run the cains script
source $CROOT/$ACTION.func
