#!/bin/bash
#
# File: sg
# Author: Chris Albrecht
# Data: 2011/oct/05
#
# Bootstrap file to run subversion and git commands simultaneously

ACTION=$1
PRE="SG:"
CROOT=~/.bash_config/global/lib/sg

# Load the global shared toolset
source ~/.bash_config/global/lib/shared/tools.inc

# We can't proceed without an action.
if [ -z "$ACTION" ]; then
  echo "$PRE No action specified."
  exit 1
fi

# Ensure the action file exists
if [ ! -f $CROOT/$ACTION.func ]; then
  echo "$PRE Action file not found."
  exit 1
fi

# Run the cains script
source $CROOT/$ACTION.func
